# -*- coding: utf-8 -*-
"""creation of a knowledge graph from CSV.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GUmnCyfT_Lv39VmygONWYWYhlge38bWT
"""

!pip install morph-kgc
!pip install yarrrml-translator

import morph_kgc
import yaml
from yarrrml_translator import translate

mapping = translate(yaml.safe_load(open("./mapping.yml")))
output_file = open("./mapping.ttl", "w")
output_file.write(mapping)
output_file.close()

g_rdflib = morph_kgc.materialize('./config.ini')

for s,p,o in g_rdflib.triples((None, None, None)):
  print(s,p,o)