# -*- coding: utf-8 -*-
"""pySHACL hands-on.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zaztcur8hgSEMCLPFhDkZAna85HK4rTX
"""

! pip3 install pyshacl

from pyshacl import validate
from rdflib import Graph

shacl_1 = Graph()
shacl_1.parse("./solution-5-1.ttl")
data = Graph()
data.parse("./data.ttl")
conforms, results_graph, results_text = validate(shacl_1,data)
print(results_text)

shacl_2 = Graph()
shacl_2.parse("./solution-5-2.ttl")
conforms, results_graph, results_text = validate(shacl_2,data)
print(results_text)

shacl_3 = Graph()
shacl_3.parse("./solution-5-3.ttl")
conforms, results_graph, results_text = validate(shacl_3,data)
print(results_text)